'use strict';
require('dotenv').config();
const crypto=require('crypto');
const {createClient}=require('@supabase/supabase-js');
const {getClass}=require('./classroom-db');
const supabase=(process.env.SUPABASE_URL&&process.env.SUPABASE_SECRET_KEY)?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SECRET_KEY):null;
const text=v=>String(v==null?'':v).trim();
const role=s=>text(s?.role).toLowerCase();
const canOperate=s=>['admin','manager'].includes(role(s));
const id=p=>`${p}-${crypto.randomUUID()}`;
function err(message,status=400,code='CLASSROOM_TEST_ERROR'){const e=new Error(message);e.statusCode=status;e.code=code;return e;}
function db(){if(!supabase)throw err('Supabase chưa được cấu hình.',503,'CLASSROOM_TEST_STORAGE_NOT_CONFIGURED');return supabase;}
function schemaError(error){const raw=String(error?.message||error||'');if(/classroom_tests|classroom_test_assignments|classroom_test_attempts|test_type|grading_status|grader_|question_order|option_orders|expires_at|relation .* does not exist|PGRST205|schema cache/i.test(raw)){return err('Database chưa có cấu trúc Bài kiểm tra Classroom mới nhất. Vui lòng chạy scripts/phf_supabase_classroom_1_23_test_stability.sql.',503,'CLASSROOM_TEST_SCHEMA_REQUIRED');}return error;}
function normalizeType(v){return ['auto','mixed','essay'].includes(text(v))?text(v):'auto';}
function normalizeQuestions(list,testType){return (Array.isArray(list)?list:[]).map((q,i)=>{const qType=['single','multiple','essay'].includes(text(q.type))?text(q.type):(testType==='essay'?'essay':'single');const points=Math.max(0.25,Number(q.points||1)||1);const base={id:text(q.id)||id('question'),type:qType,text:text(q.text),points,required:q.required!==false,sortOrder:i+1};if(qType==='essay')return {...base,maxLength:Math.max(100,Math.min(10000,Number(q.maxLength||2000)||2000)),gradingGuide:text(q.gradingGuide)};const options=(Array.isArray(q.options)?q.options:[]).map(text).filter(Boolean);const correctIndexes=(Array.isArray(q.correctIndexes)?q.correctIndexes:[q.correctIndex]).map(Number).filter(Number.isInteger);return {...base,options,correctIndexes:[...new Set(correctIndexes)].filter(x=>x>=0&&x<options.length)};}).filter(q=>q.text&&(q.type==='essay'||(q.options.length>=2&&q.correctIndexes.length)));}
function inferType(questions){const essay=questions.some(q=>q.type==='essay'),auto=questions.some(q=>q.type!=='essay');return essay&&auto?'mixed':essay?'essay':'auto';}
function mapTest(r){return {id:r.id,title:r.title||'',description:r.description||'',testType:r.test_type||inferType(Array.isArray(r.questions)?r.questions:[]),status:r.status||'draft',passScore:Number(r.pass_score||80),durationMinutes:Number(r.duration_minutes||0),maxAttempts:Number(r.max_attempts||1),shuffleQuestions:r.shuffle_questions!==false,shuffleOptions:r.shuffle_options!==false,questions:Array.isArray(r.questions)?r.questions:[],createdBy:r.created_by||'',createdAt:r.created_at||'',updatedAt:r.updated_at||''};}
function mapAssignment(r){return {id:r.id,testId:r.test_id,classId:r.class_id||'',sessionId:r.session_id||'',scopeType:r.scope_type||'independent',assignmentType:r.assignment_type||'independent',required:r.required!==false,status:r.status||'draft',openAt:r.open_at||'',closeAt:r.close_at||'',employeeIds:Array.isArray(r.employee_ids)?r.employee_ids:[],accountIds:Array.isArray(r.account_ids)?r.account_ids:[],graderEmployeeId:r.grader_employee_id||'',graderAccountId:r.grader_account_id||'',createdAt:r.created_at||'',updatedAt:r.updated_at||''};}
function mapAttempt(r){return {id:r.id,testId:r.test_id,assignmentId:r.assignment_id,employeeId:r.employee_id||'',accountId:r.account_id||'',score:Number(r.score||0),autoScore:Number(r.auto_score||0),manualScore:Number(r.manual_score||0),passed:r.passed===true,status:r.status||'submitted',gradingStatus:r.grading_status||'not_required',answers:Array.isArray(r.answers)?r.answers:[],questionOrder:Array.isArray(r.question_order)?r.question_order:[],optionOrders:r.option_orders&&typeof r.option_orders==='object'?r.option_orders:{},graderEmployeeId:r.grader_employee_id||'',graderAccountId:r.grader_account_id||'',graderComment:r.grader_comment||'',startedAt:r.started_at||'',expiresAt:r.expires_at||'',submittedAt:r.submitted_at||'',gradedAt:r.graded_at||''};}
function learnerIdentity(session){return {employeeId:text(session.employeeId),accountId:text(session.account?.id||session.sub)};}
function assignedTo(a,employeeId,accountId){return (employeeId&&(a.employeeIds||[]).includes(employeeId))||(accountId&&(a.accountIds||[]).includes(accountId));}
function assignedGrader(a,employeeId,accountId){return (employeeId&&a.graderEmployeeId===employeeId)||(accountId&&a.graderAccountId===accountId);}
function publicTest(test){return {...test,questions:(test.questions||[]).map(q=>{const x={...q};delete x.correctIndexes;return x;})};}
async function listTests(session){const client=db();const [t,a,at]=await Promise.all([client.from('classroom_tests').select('*').is('deleted_at',null).order('updated_at',{ascending:false}),client.from('classroom_test_assignments').select('*').order('updated_at',{ascending:false}),client.from('classroom_test_attempts').select('*').order('submitted_at',{ascending:false})]);if(t.error||a.error||at.error)throw schemaError(t.error||a.error||at.error);let tests=(t.data||[]).map(mapTest),assignments=(a.data||[]).map(mapAssignment),attempts=(at.data||[]).map(mapAttempt),canGrade=false;
 if(!canOperate(session)){
  const {employeeId,accountId}=learnerIdentity(session);
  const own=assignments.filter(x=>x.status==='published'&&assignedTo(x,employeeId,accountId));
  const grading=assignments.filter(x=>assignedGrader(x,employeeId,accountId));
  canGrade=grading.length>0;
  const allowedAssignments=new Set([...own,...grading].map(x=>x.id));
  const allowedTests=new Set([...own,...grading].map(x=>x.testId));
  assignments=[...new Map([...own.map(x=>({...x,canTake:true,canGrade:assignedGrader(x,employeeId,accountId)})),...grading.map(x=>({...x,canTake:assignedTo(x,employeeId,accountId),canGrade:true}))].map(x=>[x.id,x])).values()];
  tests=tests.filter(x=>x.status==='published'&&allowedTests.has(x.id)).map(publicTest);
  attempts=attempts.filter(x=>((employeeId&&x.employeeId===employeeId)||(accountId&&x.accountId===accountId))||allowedAssignments.has(x.assignmentId));
 }
 return {tests,assignments,attempts,canEdit:canOperate(session),canGrade:canOperate(session)||canGrade,serverNow:new Date().toISOString(),timezone:'Asia/Ho_Chi_Minh'};
}
async function saveTest(session,payload){if(!canOperate(session))throw err('Bạn không có quyền quản lý bài kiểm tra.',403,'CLASSROOM_OPERATION_REQUIRED');const requested=normalizeType(payload.testType);const questions=normalizeQuestions(payload.questions,requested);if(!text(payload.title))throw err('Tên bài kiểm tra không được để trống.');if(!questions.length)throw err('Bài kiểm tra phải có ít nhất một câu hỏi hợp lệ.');const actual=inferType(questions);if(requested==='auto'&&actual!=='auto')throw err('Bài trắc nghiệm tự động không được chứa câu tự luận.');if(requested==='essay'&&actual!=='essay')throw err('Bài tự luận không được chứa câu trắc nghiệm.');const row={id:text(payload.id)||id('classroom-test'),title:text(payload.title),description:text(payload.description),test_type:actual,status:['draft','published','hidden'].includes(text(payload.status))?text(payload.status):'draft',pass_score:Math.max(0,Math.min(100,Number(payload.passScore||80))),duration_minutes:Math.max(0,Number(payload.durationMinutes||0)),max_attempts:Math.max(1,Number(payload.maxAttempts||1)),shuffle_questions:payload.shuffleQuestions!==false,shuffle_options:payload.shuffleOptions!==false,questions,created_by:text(session.account?.id||session.sub||session.email),updated_at:new Date().toISOString()};const q=await db().from('classroom_tests').upsert(row,{onConflict:'id'}).select('*').single();if(q.error)throw schemaError(q.error);return {test:mapTest(q.data)};}
function isoOrNull(v,label){if(!text(v))return null;const d=new Date(v);if(Number.isNaN(d.getTime()))throw err(`${label} không hợp lệ.`);return d.toISOString();}
async function saveAssignment(session,payload){if(!canOperate(session))throw err('Bạn không có quyền giao bài kiểm tra.',403);const scopeType=['class','independent'].includes(text(payload.scopeType))?text(payload.scopeType):'independent';let classId=text(payload.classId),employeeIds=Array.isArray(payload.employeeIds)?payload.employeeIds.map(text).filter(Boolean):[],accountIds=Array.isArray(payload.accountIds)?payload.accountIds.map(text).filter(Boolean):[];
 if(scopeType==='class'){if(!classId)throw err('Vui lòng chọn lớp áp dụng.');const cls=await getClass(session,classId);employeeIds=(cls.enrollments||[]).map(x=>x.employeeId).filter(Boolean);accountIds=(cls.enrollments||[]).map(x=>x.accountId).filter(Boolean);}else if(!employeeIds.length&&!accountIds.length)throw err('Vui lòng chọn ít nhất một nhân sự nhận bài kiểm tra.');
 const testId=text(payload.testId);if(!testId)throw err('Thiếu bài kiểm tra cần giao.');const tq=await db().from('classroom_tests').select('*').eq('id',testId).single();if(tq.error)throw schemaError(tq.error);const test=mapTest(tq.data);const needsGrader=test.testType!=='auto';const graderEmployeeId=text(payload.graderEmployeeId),graderAccountId=text(payload.graderAccountId);if(needsGrader&&text(payload.status)==='published'&&!graderEmployeeId&&!graderAccountId)throw err('Bài có phần tự luận phải chỉ định người chấm trước khi phát hành.');
 const openAt=isoOrNull(payload.openAt,'Thời gian mở'),closeAt=isoOrNull(payload.closeAt,'Thời gian đóng');if(openAt&&closeAt&&new Date(closeAt)<=new Date(openAt))throw err('Thời gian đóng phải sau thời gian mở.');
 const row={id:text(payload.id)||id('test-assignment'),test_id:testId,class_id:classId||null,session_id:null,scope_type:scopeType,assignment_type:scopeType==='class'?'final':'independent',required:payload.required!==false,status:['draft','published','closed'].includes(text(payload.status))?text(payload.status):'draft',open_at:openAt,close_at:closeAt,employee_ids:employeeIds,account_ids:accountIds,grader_employee_id:graderEmployeeId||null,grader_account_id:graderAccountId||null,created_by:text(session.account?.id||session.sub||session.email),updated_at:new Date().toISOString()};const q=await db().from('classroom_test_assignments').upsert(row,{onConflict:'id'}).select('*').single();if(q.error)throw schemaError(q.error);return {assignment:mapAssignment(q.data)};}
function shuffleIndexes(n){const out=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=crypto.randomInt(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
async function startAttempt(session,payload){if(role(session)!=='learner')throw err('Chỉ học viên được bắt đầu làm bài.',403);const data=await listTests(session),assignment=data.assignments.find(x=>x.id===text(payload.assignmentId));const identity=learnerIdentity(session);if(!assignment||!assignedTo(assignment,identity.employeeId,identity.accountId))throw err('Bài kiểm tra chưa được giao cho bạn.',403);const testRow=await db().from('classroom_tests').select('*').eq('id',assignment.testId).single();if(testRow.error)throw schemaError(testRow.error);const test=mapTest(testRow.data);const now=Date.now();if(assignment.openAt&&now<new Date(assignment.openAt).getTime())throw err('Bài kiểm tra chưa đến thời gian mở.',403);if(assignment.closeAt&&now>new Date(assignment.closeAt).getTime())throw err('Bài kiểm tra đã đóng.',403);const {employeeId,accountId}=identity;const own=(data.attempts||[]).filter(x=>x.assignmentId===assignment.id&&((employeeId&&x.employeeId===employeeId)||(accountId&&x.accountId===accountId)));const active=own.find(x=>x.status==='in_progress');if(active)return {attempt:active,test:publicTest(test)};const completed=own.filter(x=>x.status!=='in_progress');if(completed.length>=test.maxAttempts)throw err('Bạn đã sử dụng hết số lần làm bài.',403);
 const stamp=new Date(),expires=test.durationMinutes>0?new Date(stamp.getTime()+test.durationMinutes*60000):null;const qOrder=test.shuffleQuestions?shuffleIndexes(test.questions.length):test.questions.map((_,i)=>i);const optionOrders={};test.questions.forEach(q=>{if(q.type!=='essay')optionOrders[q.id]=test.shuffleOptions?shuffleIndexes((q.options||[]).length):(q.options||[]).map((_,i)=>i);});const row={id:id('test-attempt'),test_id:test.id,assignment_id:assignment.id,employee_id:employeeId||null,account_id:accountId||null,score:0,auto_score:0,manual_score:0,passed:false,status:'in_progress',grading_status:'not_required',answers:[],question_order:qOrder,option_orders:optionOrders,grader_employee_id:assignment.graderEmployeeId||null,grader_account_id:assignment.graderAccountId||null,started_at:stamp.toISOString(),expires_at:expires?expires.toISOString():null,submitted_at:null};const q=await db().from('classroom_test_attempts').insert(row).select('*').single();if(q.error)throw schemaError(q.error);return {attempt:mapAttempt(q.data),test:publicTest(test)};}
function equalSets(a,b){a=[...new Set((a||[]).map(Number))].sort();b=[...new Set((b||[]).map(Number))].sort();return a.length===b.length&&a.every((x,i)=>x===b[i]);}
async function submitAttempt(session,payload){if(role(session)!=='learner')throw err('Chỉ học viên được nộp bài.',403);const client=db(),attemptId=text(payload.attemptId);if(!attemptId)throw err('Thiếu lượt làm bài. Vui lòng mở lại bài kiểm tra.');const aq=await client.from('classroom_test_attempts').select('*').eq('id',attemptId).single();if(aq.error)throw schemaError(aq.error);const attempt=mapAttempt(aq.data),identity=learnerIdentity(session);if((attempt.employeeId&&attempt.employeeId!==identity.employeeId)||(attempt.accountId&&attempt.accountId!==identity.accountId))throw err('Bạn không có quyền nộp lượt làm bài này.',403);if(attempt.status!=='in_progress')throw err('Lượt làm bài này đã được nộp hoặc không còn hiệu lực.',409);const assignmentQ=await client.from('classroom_test_assignments').select('*').eq('id',attempt.assignmentId).single();if(assignmentQ.error)throw schemaError(assignmentQ.error);const assignment=mapAssignment(assignmentQ.data),now=Date.now();if(assignment.closeAt&&now>new Date(assignment.closeAt).getTime()+10000)throw err('Bài kiểm tra đã đóng.',403);if(attempt.expiresAt&&now>new Date(attempt.expiresAt).getTime()+10000)throw err('Đã hết thời lượng làm bài. Vui lòng liên hệ người phụ trách nếu cần hỗ trợ.',403,'TEST_DURATION_EXPIRED');const tq=await client.from('classroom_tests').select('*').eq('id',attempt.testId).single();if(tq.error)throw schemaError(tq.error);const test=mapTest(tq.data);
 const raw=Array.isArray(payload.answers)?payload.answers:[];let autoEarned=0,total=0,manualTotal=0;const answers=test.questions.map((q,i)=>{const points=Number(q.points||1)||1;total+=points;const supplied=raw.find(x=>text(x.questionId)===q.id)||raw[i]||{};if(q.type==='essay'){manualTotal+=points;const answerText=text(typeof supplied==='object'?supplied.text:supplied);if(q.required!==false&&!answerText)throw err(`Vui lòng trả lời câu tự luận số ${i+1}.`);return {questionId:q.id,type:'essay',text:answerText,pointsAwarded:null};}const selected=(typeof supplied==='object'&&Array.isArray(supplied.selectedIndexes)?supplied.selectedIndexes:[supplied]).map(Number).filter(x=>x>=0);if(q.required!==false&&!selected.length)throw err(`Vui lòng trả lời câu số ${i+1}.`);const correct=equalSets(selected,q.correctIndexes||[]);if(correct)autoEarned+=points;return {questionId:q.id,type:q.type,selectedIndexes:selected,correct,pointsAwarded:correct?points:0};});
 const autoScore=total?Math.round((autoEarned/total)*10000)/100:0,needsGrading=manualTotal>0,stamp=new Date().toISOString();const row={score:autoScore,auto_score:autoScore,manual_score:0,passed:needsGrading?false:autoScore>=test.passScore,status:needsGrading?'pending_grading':'completed',grading_status:needsGrading?'pending':'not_required',answers,submitted_at:stamp};const q=await client.from('classroom_test_attempts').update(row).eq('id',attemptId).select('*').single();if(q.error)throw schemaError(q.error);return {attempt:mapAttempt(q.data),score:autoScore,passed:row.passed,pendingGrading:needsGrading};}
async function gradeAttempt(session,payload){const attemptId=text(payload.attemptId),client=db();const aq=await client.from('classroom_test_attempts').select('*').eq('id',attemptId).single();if(aq.error)throw schemaError(aq.error);const attempt=mapAttempt(aq.data);const assignmentQ=await client.from('classroom_test_assignments').select('*').eq('id',attempt.assignmentId).single();if(assignmentQ.error)throw schemaError(assignmentQ.error);const assignment=mapAssignment(assignmentQ.data);const accountId=text(session.account?.id||session.sub),employeeId=text(session.employeeId),isAdmin=role(session)==='admin';if(!isAdmin&&assignment.graderAccountId!==accountId&&assignment.graderEmployeeId!==employeeId)throw err('Bạn không phải người được chỉ định chấm bài này.',403);const testQ=await client.from('classroom_tests').select('*').eq('id',attempt.testId).single();if(testQ.error)throw schemaError(testQ.error);const test=mapTest(testQ.data);const scores=Array.isArray(payload.essayScores)?payload.essayScores:[];let earned=0,total=0;const answers=(attempt.answers||[]).map(a=>{if(a.type!=='essay')return a;const question=test.questions.find(q=>q.id===a.questionId)||{};const max=Number(question.points||0);total+=max;const found=scores.find(x=>text(x.questionId)===text(a.questionId));if(!found)throw err('Vui lòng chấm điểm đầy đủ tất cả câu tự luận.');const point=Math.max(0,Math.min(max,Number(found.points||0)));earned+=point;return {...a,pointsAwarded:point,graderNote:text(found.note)};});const totalPoints=test.questions.reduce((s,q)=>s+Number(q.points||0),0);const autoEarnedPoints=answers.filter(a=>a.type!=='essay').reduce((s,a)=>s+Number(a.pointsAwarded||0),0);const finalScore=totalPoints?Math.round(((autoEarnedPoints+earned)/totalPoints)*10000)/100:0;const stamp=new Date().toISOString();const row={answers,manual_score:total?Math.round((earned/total)*10000)/100:0,score:finalScore,passed:finalScore>=test.passScore,status:'completed',grading_status:'graded',grader_employee_id:employeeId||assignment.graderEmployeeId||null,grader_account_id:accountId||assignment.graderAccountId||null,grader_comment:text(payload.comment),graded_at:stamp};const q=await client.from('classroom_test_attempts').update(row).eq('id',attemptId).select('*').single();if(q.error)throw schemaError(q.error);return {attempt:mapAttempt(q.data)};}
module.exports={listTests,saveTest,saveAssignment,startAttempt,submitAttempt,gradeAttempt};
