begin;

create table if not exists public.checklist_repeat_violation_policies (
  id uuid primary key default gen_random_uuid(),
  effective_from_period text not null unique
    check (effective_from_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  monthly_warning_count integer not null default 2
    check (monthly_warning_count between 2 and 20),
  training_occurrence_count integer not null default 3
    check (training_occurrence_count between 2 and 50),
  training_window_months integer not null default 3
    check (training_window_months between 1 and 12),
  reason text not null default '',
  is_active boolean not null default true,
  created_by text not null default '',
  created_by_code text not null default '',
  created_by_name text not null default '',
  created_at timestamptz not null default now(),
  updated_by text not null default '',
  updated_by_code text not null default '',
  updated_by_name text not null default '',
  updated_at timestamptz not null default now(),
  constraint checklist_repeat_policy_threshold_order
    check (training_occurrence_count >= monthly_warning_count)
);

create index if not exists idx_checklist_repeat_violation_policies_effective
  on public.checklist_repeat_violation_policies(is_active, effective_from_period desc);

create table if not exists public.checklist_repeat_violation_policy_history (
  id bigint generated by default as identity primary key,
  policy_id uuid references public.checklist_repeat_violation_policies(id) on update cascade on delete restrict,
  effective_from_period text not null,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  reason text not null default '',
  changed_by text not null default '',
  changed_by_code text not null default '',
  changed_by_name text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists idx_checklist_repeat_violation_policy_history_changed
  on public.checklist_repeat_violation_policy_history(changed_at desc);

insert into public.checklist_repeat_violation_policies (
  effective_from_period,
  monthly_warning_count,
  training_occurrence_count,
  training_window_months,
  reason,
  created_by_name,
  updated_by_name
) values (
  '2026-08',
  2,
  3,
  3,
  'Khởi tạo ngưỡng lỗi lặp lại và gợi ý đào tạo từ kỳ 08/2026.',
  'PHF Checklist 1.32.27',
  'PHF Checklist 1.32.27'
)
on conflict (effective_from_period) do nothing;

comment on table public.checklist_repeat_violation_policies is
  'Cấu hình ngưỡng cảnh báo lỗi lặp và gợi ý đào tạo theo kỳ. Chỉ tạo gợi ý trong Checklist, không tự liên kết PHF Class.';
comment on column public.checklist_repeat_violation_policies.monthly_warning_count is
  'Số lần cùng nhân viên + cùng tiêu chí trong một kỳ để cảnh báo.';
comment on column public.checklist_repeat_violation_policies.training_occurrence_count is
  'Tổng số lần trong cửa sổ theo dõi để gợi ý Admin xem xét đào tạo.';
comment on column public.checklist_repeat_violation_policies.training_window_months is
  'Số tháng lịch tính đến kỳ được xem; chỉ dùng dữ liệu chính thức, không dùng TEST hoặc lỗi đã hủy.';
comment on table public.checklist_repeat_violation_policy_history is
  'Lịch sử trước-sau mỗi lần Admin thay đổi ngưỡng lỗi lặp lại.';

alter table public.checklist_repeat_violation_policies enable row level security;
alter table public.checklist_repeat_violation_policy_history enable row level security;

revoke all on table public.checklist_repeat_violation_policies from public, anon, authenticated;
revoke all on table public.checklist_repeat_violation_policy_history from public, anon, authenticated;
grant all on table public.checklist_repeat_violation_policies to service_role;
grant all on table public.checklist_repeat_violation_policy_history to service_role;
grant usage, select on sequence public.checklist_repeat_violation_policy_history_id_seq to service_role;

commit;

select effective_from_period, monthly_warning_count, training_occurrence_count,
       training_window_months, reason, updated_by_name, updated_at
from public.checklist_repeat_violation_policies
order by effective_from_period desc;
