-- PHF Classroom 1.18 - Nhóm nội dung, tài liệu Supabase Storage và tiến độ đọc
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('phf-classroom','phf-classroom',false,26214400,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create table if not exists public.classroom_content_groups(id text primary key,class_id text not null references public.classroom_classes(id) on delete cascade,title text not null,description text,status text not null default 'draft' check(status in ('draft','published','hidden')),sort_order integer not null default 0,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists classroom_content_groups_class_idx on public.classroom_content_groups(class_id,sort_order);
create table if not exists public.classroom_materials(id text primary key,class_id text not null references public.classroom_classes(id) on delete cascade,group_id text not null references public.classroom_content_groups(id) on delete cascade,title text not null,original_name text not null,mime_type text not null,size_bytes bigint not null,storage_path text not null unique,required boolean not null default true,status text not null default 'draft' check(status in ('draft','published','hidden')),sort_order integer not null default 0,version_no integer not null default 1,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists classroom_materials_class_idx on public.classroom_materials(class_id,group_id,sort_order);
create table if not exists public.classroom_material_versions(id text primary key,material_id text not null references public.classroom_materials(id) on delete cascade,version_no integer not null,storage_path text not null,original_name text,mime_type text,size_bytes bigint,changed_by text,change_reason text,created_at timestamptz not null default now(),unique(material_id,version_no));
create table if not exists public.classroom_material_progress(id text primary key,class_id text not null references public.classroom_classes(id) on delete cascade,material_id text not null references public.classroom_materials(id) on delete cascade,enrollment_id text not null references public.classroom_enrollments(id) on delete cascade,employee_id text,account_id text,status text not null default 'not_started' check(status in ('not_started','opened','completed')),first_opened_at timestamptz,last_opened_at timestamptz,confirmed_at timestamptz,updated_at timestamptz not null default now(),unique(material_id,enrollment_id));
create index if not exists classroom_material_progress_class_idx on public.classroom_material_progress(class_id,enrollment_id);
