begin;

create table if not exists public.checklist_late_point_policies (
  id uuid primary key default gen_random_uuid(),
  effective_from_period text not null unique
    check (effective_from_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  levels jsonb not null,
  reason text not null default '',
  is_active boolean not null default true,
  created_by text not null default '',
  created_by_code text not null default '',
  created_by_name text not null default '',
  created_at timestamptz not null default now(),
  updated_by text not null default '',
  updated_by_code text not null default '',
  updated_by_name text not null default '',
  updated_at timestamptz not null default now(),
  constraint checklist_late_point_policies_levels_array
    check (jsonb_typeof(levels) = 'array')
);

create index if not exists idx_checklist_late_point_policies_effective
  on public.checklist_late_point_policies(is_active, effective_from_period desc);

create table if not exists public.checklist_late_point_policy_history (
  id bigint generated by default as identity primary key,
  policy_id uuid references public.checklist_late_point_policies(id) on update cascade on delete restrict,
  effective_from_period text not null,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  reason text not null default '',
  changed_by text not null default '',
  changed_by_code text not null default '',
  changed_by_name text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists idx_checklist_late_point_policy_history_changed
  on public.checklist_late_point_policy_history(changed_at desc);

insert into public.checklist_late_point_policies (
  effective_from_period,
  levels,
  reason,
  created_by_name,
  updated_by_name
) values (
  '2026-08',
  '[
    {"minMinutes":1,"maxMinutes":5,"points":1},
    {"minMinutes":6,"maxMinutes":15,"points":2},
    {"minMinutes":16,"maxMinutes":30,"points":3},
    {"minMinutes":31,"maxMinutes":null,"points":5}
  ]'::jsonb,
  'Khởi tạo bảng mức Đi trễ hiện hành từ kỳ 08/2026.',
  'PHF Checklist 1.32.26',
  'PHF Checklist 1.32.26'
)
on conflict (effective_from_period) do nothing;

comment on table public.checklist_late_point_policies is
  'Các phiên bản bảng mức điểm chuẩn Đi trễ theo kỳ áp dụng. Bản ghi cũ không bị hồi tố.';
comment on column public.checklist_late_point_policies.levels is
  'Danh sách khoảng phút liên tục. Mức cuối có maxMinutes = null để bao phủ trở lên.';
comment on table public.checklist_late_point_policy_history is
  'Lịch sử trước-sau mỗi lần Admin thay đổi bảng mức Đi trễ.';

alter table public.checklist_late_point_policies enable row level security;
alter table public.checklist_late_point_policy_history enable row level security;

revoke all on table public.checklist_late_point_policies from public, anon, authenticated;
revoke all on table public.checklist_late_point_policy_history from public, anon, authenticated;
grant all on table public.checklist_late_point_policies to service_role;
grant all on table public.checklist_late_point_policy_history to service_role;

grant usage, select on sequence public.checklist_late_point_policy_history_id_seq to service_role;

commit;

select effective_from_period, levels, reason, updated_by_name, updated_at
from public.checklist_late_point_policies
order by effective_from_period desc;
