begin;

create table if not exists public.checklist_monthly_score_policies (
  id uuid primary key default gen_random_uuid(),
  effective_from_period text not null unique
    check (effective_from_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  self_weight numeric(8,2) not null default 1
    check (self_weight >= 0 and self_weight <= 100),
  review_weight numeric(8,2) not null default 2
    check (review_weight >= 0 and review_weight <= 100),
  reason text not null default '',
  is_active boolean not null default true,
  created_by text not null default '',
  created_by_code text not null default '',
  created_by_name text not null default '',
  created_at timestamptz not null default now(),
  updated_by text not null default '',
  updated_by_code text not null default '',
  updated_by_name text not null default '',
  updated_at timestamptz not null default now(),
  constraint checklist_monthly_score_policy_total_positive
    check ((self_weight + review_weight) > 0)
);

create index if not exists idx_checklist_monthly_score_policies_effective
  on public.checklist_monthly_score_policies(is_active, effective_from_period desc);

create table if not exists public.checklist_monthly_score_policy_history (
  id bigint generated by default as identity primary key,
  policy_id uuid references public.checklist_monthly_score_policies(id)
    on update cascade on delete restrict,
  effective_from_period text not null,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  reason text not null default '',
  changed_by text not null default '',
  changed_by_code text not null default '',
  changed_by_name text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists idx_checklist_monthly_score_policy_history_changed
  on public.checklist_monthly_score_policy_history(changed_at desc);

alter table public.checklist_monthly_periods
  add column if not exists score_policy_snapshot jsonb not null default
  '{"effectiveFromPeriod":"2026-08","selfWeight":1,"reviewWeight":2,"totalWeight":3,"formulaVersion":"weighted_average_v1"}'::jsonb;

alter table public.checklist_monthly_forms
  add column if not exists score_policy_snapshot jsonb not null default
  '{"effectiveFromPeriod":"2026-08","selfWeight":1,"reviewWeight":2,"totalWeight":3,"formulaVersion":"weighted_average_v1"}'::jsonb;

insert into public.checklist_monthly_score_policies (
  effective_from_period,
  self_weight,
  review_weight,
  reason,
  created_by_name,
  updated_by_name
) values (
  '2026-08',
  1,
  2,
  'Khởi tạo trọng số phiếu đánh giá tháng 1:2 từ kỳ 08/2026.',
  'PHF Checklist 1.32.28',
  'PHF Checklist 1.32.28'
)
on conflict (effective_from_period) do nothing;

comment on table public.checklist_monthly_score_policies is
  'Phiên bản trọng số Tự đánh giá và Thẩm định theo kỳ. Không cho nhập công thức tự do.';
comment on column public.checklist_monthly_periods.score_policy_snapshot is
  'Bản chụp trọng số của kỳ; không thay đổi khi Admin cập nhật chính sách về sau.';
comment on column public.checklist_monthly_forms.score_policy_snapshot is
  'Bản chụp trọng số trên từng phiếu để tính và truy vết kết quả cuối.';
comment on table public.checklist_monthly_score_policy_history is
  'Lịch sử trước-sau mỗi lần Admin thay đổi trọng số phiếu tháng.';

alter table public.checklist_monthly_score_policies enable row level security;
alter table public.checklist_monthly_score_policy_history enable row level security;

revoke all on table public.checklist_monthly_score_policies from public, anon, authenticated;
revoke all on table public.checklist_monthly_score_policy_history from public, anon, authenticated;
grant all on table public.checklist_monthly_score_policies to service_role;
grant all on table public.checklist_monthly_score_policy_history to service_role;
grant usage, select on sequence public.checklist_monthly_score_policy_history_id_seq to service_role;

commit;

select effective_from_period, self_weight, review_weight, reason, updated_by_name, updated_at
from public.checklist_monthly_score_policies
order by effective_from_period desc;
